# -------------------hicoin-web-api Deployment ------------------- #

###LOCAL##AWS##
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  labels:
    k8s-app: hicoin-test
  name: hicoin-test
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: hicoin-test
  template:
    metadata:
      labels:
        k8s-app: hicoin-test
    spec:
      containers:
      - name: hicoin-test
        image: ${REGISTRY_API}/hicoin:test.build-${BUILD_NUMBER}
        ports:
        - containerPort: 10000
          protocol: TCP
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: "Production"
        tty: true

