# ------------------- hicoin-web-api Service ------------------- #
kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: hicoin-test
  name: hicoin-test
  namespace: default
spec:    
  type: NodePort
  ports:
  - port: 10000
    targetPort: 10000
    nodePort: 20210
  selector:
    k8s-app: hicoin-test
