# ------------------- hicoin-web-api Service ------------------- #
kind: Service
apiVersion: v1
metadata:
  labels:
    k8s-app: hicoin-nameserver
  name: hicoin-nameserver
  namespace: default
spec:    
  ports:
    - port: 10000
      targetPort: 10000
  selector:
    k8s-app: hicoin-nameserver
